version: '2.2'

services:
  groca:
    build: ./first-react-app
    container_name: Groca_c
    ports:
      - '3000:3000'
    volumes:
      - /groca/node_modules
      - ./first-react-app:/groca
    stdin_open: true
    tty: true